server:
  port: "8080"
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

postgres:
  host: "localhost"
  port: "5432"
  dbname: "documents"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  db: 0

jwt:
  expiration: 24h

migrations:
  path: "internal/repository/postgres/migrations"